// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class BranchesSubjectsJunctions
{
    public string Id { get; set; }

    public string Branch { get; set; }

    public string Subject { get; set; }

    public virtual SchoolBranchs BranchNavigation { get; set; }

    public virtual Subjects SubjectNavigation { get; set; }
}