// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class ExerciseSheetQuestionJunction
{
    public string Id { get; set; }

    public string ExerciseSheet { get; set; }

    public string Question { get; set; }

    public virtual ExerciseSheets ExerciseSheetNavigation { get; set; }

    public virtual Questions QuestionNavigation { get; set; }
}