// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class ExerciseSheets
{
    public string Id { get; set; }

    public string Tilte { get; set; }

    public string Teacher { get; set; }

    public string Topic { get; set; }

    public bool NamePlaceHolder { get; set; }

    public bool MarkPlaceHolder { get; set; }

    public bool DatePlaceHolder { get; set; }

    public bool ClassNumberPlaceHolder { get; set; }

    public string ClassNumberText { get; set; }

    public bool SubjectPlaceHolder { get; set; }

    public virtual ICollection<ExerciseSheetQuestionJunction> ExerciseSheetQuestionJunction { get; set; } = new List<ExerciseSheetQuestionJunction>();
}