// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class FoldersQuestionsJunction
{
    public string Folder { get; set; }

    public string Question { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual Folders FolderNavigation { get; set; }

    public virtual Questions QuestionNavigation { get; set; }
}