// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class QuestionDifficultyLevels
{
    public string Id { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();
}