// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Questions
{
    public string Id { get; set; }

    public string QuestionText { get; set; }

    public string Answer { get; set; }

    public string Author { get; set; }

    public string DifficultyLevel { get; set; }

    public int SchoolLevel { get; set; }

    public string Topic { get; set; }

    public bool QuestionIsPrivate { get; set; }

    public string InnerHtml { get; set; }

    public int SchoolType { get; set; }

    public string SchoolBranch { get; set; }

    public virtual Teachers AuthorNavigation { get; set; }

    public virtual QuestionDifficultyLevels DifficultyLevelNavigation { get; set; }

    public virtual ICollection<ExerciseSheetQuestionJunction> ExerciseSheetQuestionJunction { get; set; } = new List<ExerciseSheetQuestionJunction>();

    public virtual ICollection<FoldersQuestionsJunction> FoldersQuestionsJunction { get; set; } = new List<FoldersQuestionsJunction>();

    public virtual SchoolBranches SchoolBranchNavigation { get; set; }

    public virtual SchoolLevels SchoolLevelNavigation { get; set; }

    public virtual SchoolTypes SchoolTypeNavigation { get; set; }

    public virtual Topics TopicNavigation { get; set; }
}