// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Questions
{
    public string id { get; set; }

    public string content { get; set; }

    public string answer { get; set; }

    public string author { get; set; }

    public string difficultyLevel { get; set; }

    public int schoolLevel { get; set; }

    public string topic { get; set; }

    public virtual Teachers authorNavigation { get; set; }

    public virtual QuestionDifficultyLevels difficultyLevelNavigation { get; set; }

    public virtual SchoolLevels schoolLevelNavigation { get; set; }

    public virtual Topics topicNavigation { get; set; }
}