// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolsSubjectsJunctions
{
    public string id { get; set; }

    public string school { get; set; }

    public string subject { get; set; }

    public virtual Schools schoolNavigation { get; set; }

    public virtual Subjects subjectNavigation { get; set; }
}