// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolTypes
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Schools> Schools { get; set; } = new List<Schools>();
}