// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolBranches
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BranchesSubjectsJunction> BranchesSubjectsJunctions { get; set; } = new List<BranchesSubjectsJunction>();

    public virtual ICollection<SchoolsBranchesJunction> SchoolsBranchesJunctions { get; set; } = new List<SchoolsBranchesJunction>();
}