// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolBranchs
{
    public string id { get; set; }

    public string name { get; set; }

    public virtual ICollection<BranchesSubjectsJunctions> BranchesSubjectsJunctions { get; set; } = new List<BranchesSubjectsJunctions>();

    public virtual ICollection<SchoolsBranchesJunctions> SchoolsBranchesJunctions { get; set; } = new List<SchoolsBranchesJunctions>();
}