// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Schools
{
    public string Name { get; set; }

    public string SchoolType { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual SchoolTypes SchoolTypeNavigation { get; set; }

    public virtual ICollection<SchoolsBranchesJunction> SchoolsBranchesJunctions { get; set; } = new List<SchoolsBranchesJunction>();

    public virtual ICollection<SchoolsLevelsJunction> SchoolsLevelsJunctions { get; set; } = new List<SchoolsLevelsJunction>();

    public virtual ICollection<SchoolsSubjectsJunction> SchoolsSubjectsJunctions { get; set; } = new List<SchoolsSubjectsJunction>();

    public virtual ICollection<Teachers> Teachers { get; set; } = new List<Teachers>();
}