// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolsBranchesJunctions
{
    public string id { get; set; }

    public string school { get; set; }

    public string branch { get; set; }

    public virtual SchoolBranchs branchNavigation { get; set; }

    public virtual Schools schoolNavigation { get; set; }
}