// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class SchoolTypes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();

    public virtual ICollection<SchoolTypesLevelsJunction> SchoolTypesLevelsJunction { get; set; } = new List<SchoolTypesLevelsJunction>();

    public virtual ICollection<Schools> Schools { get; set; } = new List<Schools>();
}