// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Subjects
{
    public string id { get; set; }

    public string name { get; set; }

    public string shortcut { get; set; }

    public virtual ICollection<BranchesSubjectsJunctions> BranchesSubjectsJunctions { get; set; } = new List<BranchesSubjectsJunctions>();

    public virtual ICollection<SchoolsSubjectsJunctions> SchoolsSubjectsJunctions { get; set; } = new List<SchoolsSubjectsJunctions>();

    public virtual ICollection<TeachersSubjectsJunctions> TeachersSubjectsJunctions { get; set; } = new List<TeachersSubjectsJunctions>();

    public virtual ICollection<Topics> Topics { get; set; } = new List<Topics>();
}