// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Subjects
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Shortcut { get; set; }

    public virtual ICollection<BranchesSubjectsJunction> BranchesSubjectsJunctions { get; set; } = new List<BranchesSubjectsJunction>();

    public virtual ICollection<SchoolsSubjectsJunction> SchoolsSubjectsJunctions { get; set; } = new List<SchoolsSubjectsJunction>();

    public virtual ICollection<TeachersSubjectsJunction> TeachersSubjectsJunctions { get; set; } = new List<TeachersSubjectsJunction>();

    public virtual ICollection<Topics> Topics { get; set; } = new List<Topics>();
}