// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Domain.Entities;

public partial class Teachers
{
    public string Surname { get; set; }

    public string FamilyName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string School { get; set; }

    public bool IsActive { get; set; }

    public string Branch { get; set; }

    public virtual SchoolBranches BranchNavigation { get; set; }

    public virtual ICollection<ExerciseSheets> ExerciseSheets { get; set; } = new List<ExerciseSheets>();

    public virtual ICollection<Folders> Folders { get; set; } = new List<Folders>();

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();

    public virtual Schools SchoolNavigation { get; set; }

    public virtual ICollection<TeachersHiddenQuestions> TeachersHiddenQuestions { get; set; } = new List<TeachersHiddenQuestions>();

    public virtual ICollection<TeachersSchoolLevelsJunction> TeachersSchoolLevelsJunction { get; set; } = new List<TeachersSchoolLevelsJunction>();

    public virtual ICollection<TeachersSubjectsJunction> TeachersSubjectsJunction { get; set; } = new List<TeachersSubjectsJunction>();
}