// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class BranchesSubjectsJunctions
{
    public string id { get; set; }

    public string branch { get; set; }

    public string subject { get; set; }

    public virtual SchoolBranchs branchNavigation { get; set; }

    public virtual Subjects subjectNavigation { get; set; }
}