// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class BranchSubjectJunction
{
    public string Id { get; set; }

    public string Branch { get; set; }

    public string Subject { get; set; }

    public virtual SchoolBranch BranchNavigation { get; set; }

    public virtual Subject SubjectNavigation { get; set; }
}