// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class QuestionDifficultyLevels
{
    public string id { get; set; }

    public string description { get; set; }

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();
}