// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class Question
{
    public string Id { get; set; }

    public string Content { get; set; }

    public string Answer { get; set; }

    public string Author { get; set; }

    public string DifficultyLevel { get; set; }

    public string SchoolLevel { get; set; }

    public string Topic { get; set; }

    public virtual Teacher AuthorNavigation { get; set; }

    public virtual QuestionDifficultyLevel DifficultyLevelNavigation { get; set; }

    public virtual Topic IdNavigation { get; set; }

    public virtual SchoolLevel SchoolLevelNavigation { get; set; }
}