// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class SchoolLevels
{
    public int level { get; set; }

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();

    public virtual ICollection<SchoolsLevelsJunctions> SchoolsLevelsJunctions { get; set; } = new List<SchoolsLevelsJunctions>();

    public virtual ICollection<TeachersSchoolLevelsJunctions> TeachersSchoolLevelsJunctions { get; set; } = new List<TeachersSchoolLevelsJunctions>();
}