// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class SchoolsLevelsJunctions
{
    public string id { get; set; }

    public string school { get; set; }

    public int schoolLevel { get; set; }

    public virtual SchoolLevels schoolLevelNavigation { get; set; }

    public virtual Schools schoolNavigation { get; set; }
}