// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class SchoolsLevelsJunction
{
    public string Id { get; set; }

    public string School { get; set; }

    public string SchoolLevel { get; set; }
}