// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class Subject
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BranchSubjectJunction> BranchSubjectJunctions { get; set; } = new List<BranchSubjectJunction>();

    public virtual ICollection<SchoolsSubjectsJunction> SchoolsSubjectsJunctions { get; set; } = new List<SchoolsSubjectsJunction>();

    public virtual ICollection<TeachersSubjectsJunction> TeachersSubjectsJunctions { get; set; } = new List<TeachersSubjectsJunction>();

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}