// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class TeachersSubjectsJunctions
{
    public string id { get; set; }

    public string teacher { get; set; }

    public string subject { get; set; }

    public virtual Subjects subjectNavigation { get; set; }

    public virtual Teachers teacherNavigation { get; set; }
}