// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class Teacher
{
    public string Id { get; set; }

    public string Surname { get; set; }

    public string FamilyName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string School { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual Schools SchoolNavigation { get; set; }

    public virtual TeachersSchoolLevelsJunction TeachersSchoolLevelsJunction { get; set; }

    public virtual ICollection<TeachersSubjectsJunction> TeachersSubjectsJunctions { get; set; } = new List<TeachersSubjectsJunction>();
}