// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace exerciseBox.Infrastructur.Models;

public partial class TeachersSchoolLevelsJunction
{
    public string Id { get; set; }

    public string Teacher { get; set; }

    public string SchoolLevel { get; set; }

    public virtual Teacher IdNavigation { get; set; }

    public virtual SchoolLevel SchoolLevelNavigation { get; set; }
}